name: daily
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  lints: ^3.0.0

flutter:
  uses-material-design: true
