
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGtyURAiOiaQZO0m_T8CVR_XRr-4MI0A',
    appId: '1:235289225846:web:a3e5c7e9327d28982c4d57',
    messagingSenderId: '235289225846',
    projectId: 'tasklist-821cd',
    authDomain: 'tasklist-821cd.firebaseapp.com',
    storageBucket: 'tasklist-821cd.firebasestorage.app',
    measurementId: 'G-2Y7SH1E6KV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXB8f0wFfikERqKN7lI2Zmrzk_ilibIps',
    appId: '1:235289225846:ios:3db7c23faf395fcf2c4d57',
    messagingSenderId: '235289225846',
    projectId: 'tasklist-821cd',
    storageBucket: 'tasklist-821cd.firebasestorage.app',
    iosBundleId: 'com.example.daily',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXB8f0wFfikERqKN7lI2Zmrzk_ilibIps',
    appId: '1:235289225846:ios:3db7c23faf395fcf2c4d57',
    messagingSenderId: '235289225846',
    projectId: 'tasklist-821cd',
    storageBucket: 'tasklist-821cd.firebasestorage.app',
    iosBundleId: 'com.example.daily',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK6I_3JSSzYFiU96d-nKT3dx3uCkVj4Do',
    appId: '1:235289225846:android:f04368b1237866502c4d57',
    messagingSenderId: '235289225846',
    projectId: 'tasklist-821cd',
    storageBucket: 'tasklist-821cd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGGtyURAiOiaQZO0m_T8CVR_XRr-4MI0A',
    appId: '1:235289225846:web:3b7985c73d2355642c4d57',
    messagingSenderId: '235289225846',
    projectId: 'tasklist-821cd',
    authDomain: 'tasklist-821cd.firebaseapp.com',
    storageBucket: 'tasklist-821cd.firebasestorage.app',
    measurementId: 'G-2ZW74PHM9X',
  );

}